sudo: false

language: python

cache:
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - python: "3.5"
      env: TOXENV=py35

    # Meta
    - python: "3.5"
      env: TOXENV=flake8
    - python: "3.5"
      env: TOXENV=readme

install:
  - pip install tox

before_install:
  - pip install codecov

after_success:
  - tox -e coverage-report
  - codecov

script:
  - tox
